name: Django project deploy

on:
  push:
    branches: [master]

jobs:
  server_update:
    name: Доставка изменений
    runs-on: ubuntu-latest
    steps:
      - name: Запуск скрипта обновления
        working-directory: /opt/app/dj_cicd/
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: bash update.sh

# jobs:
#   tests:
#     steps:
#      - name: Деплой
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          script: expect /home/adilet/url_shortener/pull.exp
